export const students = [
  {
    id: 1,
    awardee_name: "Samantha Rodriguez",
    ranking: "Highest Honor",
    avg: "98.10%",
    quarter: "2nd",
    school_year: "2023-2024",
    school_name: "Willowbrook Preparatory Academy",
    signatory_name1: "Joshua Martinez",
    signatory_position1: "class adviser",
    signatory_name2: "Isabella Garcia",
    signatory_position2: "academic head",
    present_date: "05-21-2024",
  },
  {
    id: 2,
    awardee_name: "Ethan Thompson",
    ranking: "Highest Honor",
    avg: "96.50%",
    quarter: "2nd",
    school_year: "2023-2024",
    school_name: "Willowbrook Preparatory Academy",
    signatory_name1: "Joshua Martinez",
    signatory_position1: "class adviser",
    signatory_name2: "Isabella Garcia",
    signatory_position2: "academic head",
    present_date: "05-21-2024",
  },
  {
    id: 3,
    awardee_name: "Emily Johnson",
    ranking: "Highest Honor",
    avg: "97.80%",
    quarter: "2nd",
    school_year: "2023-2024",
    school_name: "Willowbrook Preparatory Academy",
    signatory_name1: "Joshua Martinez",
    signatory_position1: "class adviser",
    signatory_name2: "Isabella Garcia",
    signatory_position2: "academic head",
    present_date: "05-21-2024",
  },
  {
    id: 4,
    awardee_name: "Jacob Smith",
    ranking: "High Honor",
    avg: "95.20%",
    quarter: "2nd",
    school_year: "2023-2024",
    school_name: "Willowbrook Preparatory Academy",
    signatory_name1: "Joshua Martinez",
    signatory_position1: "class adviser",
    signatory_name2: "Isabella Garcia",
    signatory_position2: "academic head",
    present_date: "05-21-2024",
  },
  {
    id: 5,
    awardee_name: "Olivia Brown",
    ranking: "Honor",
    avg: "94.70%",
    quarter: "2nd",
    school_year: "2023-2024",
    school_name: "Willowbrook Preparatory Academy",
    signatory_name1: "Joshua Martinez",
    signatory_position1: "class adviser",
    signatory_name2: "Isabella Garcia",
    signatory_position2: "academic head",
    present_date: "05-21-2024",
  },
  {
    id: 6,
    awardee_name: "Aiden Wilson",
    ranking: "Highest Honor",
    avg: "97.20%",
    quarter: "2nd",
    school_year: "2023-2024",
    school_name: "Willowbrook Preparatory Academy",
    signatory_name1: "Joshua Martinez",
    signatory_position1: "class adviser",
    signatory_name2: "Isabella Garcia",
    signatory_position2: "academic head",
    present_date: "05-21-2024",
  },
  {
    id: 7,
    awardee_name: "Sophia Martinez",
    ranking: "High Honor",
    avg: "95.80%",
    quarter: "2nd",
    school_year: "2023-2024",
    school_name: "Willowbrook Preparatory Academy",
    signatory_name1: "Joshua Martinez",
    signatory_position1: "class adviser",
    signatory_name2: "Isabella Garcia",
    signatory_position2: "academic head",
    present_date: "05-21-2024",
  },
  {
    id: 8,
    awardee_name: "Logan Taylor",
    ranking: "High Honor",
    avg: "96.90%",
    quarter: "2nd",
    school_year: "2023-2024",
    school_name: "Willowbrook Preparatory Academy",
    signatory_name1: "Joshua Martinez",
    signatory_position1: "class adviser",
    signatory_name2: "Isabella Garcia",
    signatory_position2: "academic head",
    present_date: "05-21-2024",
  },
  {
    id: 9,
    awardee_name: "Mia Hernandez",
    ranking: "Honor",
    avg: "94.30%",
    quarter: "2nd",
    school_year: "2023-2024",
    school_name: "Willowbrook Preparatory Academy",
    signatory_name1: "Joshua Martinez",
    signatory_position1: "class adviser",
    signatory_name2: "Isabella Garcia",
    signatory_position2: "academic head",
    present_date: "05-21-2024",
  },
  {
    id: 10,
    awardee_name: "Lucas Gonzalez",
    ranking: "Highest Honor",
    avg: "98.70%",
    quarter: "2nd",
    school_year: "2023-2024",
    school_name: "Willowbrook Preparatory Academy",
    signatory_name1: "Joshua Martinez",
    signatory_position1: "class adviser",
    signatory_name2: "Isabella Garcia",
    signatory_position2: "academic head",
    present_date: "05-21-2024",
  },
];
