export const students = [
  {
    id: 1,
    student_full_name: "Samantha Rodriguez",
    certificate_type: "Highest Honor",
    avg: "98.10%",
    quarter: "2nd",
    school_year: "2023-2024",
    school_name: "Willowbrook Preparatory Academy",
    adviser_full_name: "Joshua Martinez",
    principal_full_name: "Isabella Garcia",
    present_date: "05-21-2024",
  },
  {
    id: 2,
    student_full_name: "Ethan Thompson",
    certificate_type: "Highest Honor",
    avg: "96.50%",
    quarter: "2nd",
    school_year: "2023-2024",
    school_name: "Willowbrook Preparatory Academy",
    adviser_full_name: "Joshua Martinez",
    principal_full_name: "Isabella Garcia",
    present_date: "05-21-2024",
  },
  {
    id: 3,
    student_full_name: "Emily Johnson",
    certificate_type: "Highest Honor",
    avg: "97.80%",
    quarter: "2nd",
    school_year: "2023-2024",
    school_name: "Willowbrook Preparatory Academy",
    adviser_full_name: "Joshua Martinez",
    principal_full_name: "Isabella Garcia",
    present_date: "05-21-2024",
  },
  {
    id: 4,
    student_full_name: "Jacob Smith",
    certificate_type: "Highest Honor",
    avg: "95.20%",
    quarter: "2nd",
    school_year: "2023-2024",
    school_name: "Willowbrook Preparatory Academy",
    adviser_full_name: "Joshua Martinez",
    principal_full_name: "Isabella Garcia",
    present_date: "05-21-2024",
  },
  {
    id: 5,
    student_full_name: "Olivia Brown",
    certificate_type: "Highest Honor",
    avg: "94.70%",
    quarter: "2nd",
    school_year: "2023-2024",
    school_name: "Willowbrook Preparatory Academy",
    adviser_full_name: "Joshua Martinez",
    principal_full_name: "Isabella Garcia",
    present_date: "05-21-2024",
  },
  {
    id: 6,
    student_full_name: "Aiden Wilson",
    certificate_type: "Highest Honor",
    avg: "97.20%",
    quarter: "2nd",
    school_year: "2023-2024",
    school_name: "Willowbrook Preparatory Academy",
    adviser_full_name: "Joshua Martinez",
    principal_full_name: "Isabella Garcia",
    present_date: "05-21-2024",
  },
  {
    id: 7,
    student_full_name: "Sophia Martinez",
    certificate_type: "Highest Honor",
    avg: "95.80%",
    quarter: "2nd",
    school_year: "2023-2024",
    school_name: "Willowbrook Preparatory Academy",
    adviser_full_name: "Joshua Martinez",
    principal_full_name: "Isabella Garcia",
    present_date: "05-21-2024",
  },
  {
    id: 8,
    student_full_name: "Logan Taylor",
    certificate_type: "Highest Honor",
    avg: "96.90%",
    quarter: "2nd",
    school_year: "2023-2024",
    school_name: "Willowbrook Preparatory Academy",
    adviser_full_name: "Joshua Martinez",
    principal_full_name: "Isabella Garcia",
    present_date: "05-21-2024",
  },
  {
    id: 9,
    student_full_name: "Mia Hernandez",
    certificate_type: "Highest Honor",
    avg: "94.30%",
    quarter: "2nd",
    school_year: "2023-2024",
    school_name: "Willowbrook Preparatory Academy",
    adviser_full_name: "Joshua Martinez",
    principal_full_name: "Isabella Garcia",
    present_date: "05-21-2024",
  },
  {
    id: 10,
    student_full_name: "Lucas Gonzalez",
    certificate_type: "Highest Honor",
    avg: "98.70%",
    quarter: "2nd",
    school_year: "2023-2024",
    school_name: "Willowbrook Preparatory Academy",
    adviser_full_name: "Joshua Martinez",
    principal_full_name: "Isabella Garcia",
    present_date: "05-21-2024",
  },
];
